### PR TITLE
add translation Bahasa Indonesia, locale id

### PR DESCRIPTION
**Pull request by oonid**
hi, I would like to contribute a translation to this project, Bahasa Indonesia (Indonesian Language), locale ID.
hopefully next time it would be available on Transifex or Weblate, to make contribution easier.

I have translated [django.po on Polaris](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/locale/pt/LC_MESSAGES/django.po) and [django.po on the example](https://github.com/stellar/django-polaris/blob/master/example/server/locale/pt/LC_MESSAGES/django.po) with Lokalize (KDE app), so it also updates the mo files.

please review and comment if I need to revise it.

thank you.

### CODE REVIEW

**Comment by oonid** [comment]
hi @JakeUrban 
thank you. Sure, I will maintain the translation.
as I mentioned before, please use translation service, so it would be easier to track changes in the strings.

yes, Weblate has "[Libre plan](https://weblate.org/en/hosting/)" for open source project.
I have translated several open-source projects to Bahasa Indonesia at Weblate also Transifex, including Python and Django.

I have added the `LANGUAGES` on `settings.py`.

please let me know if there's some additional revision.

**Comment by JakeUrban** [comment]
I'll be releasing 0.13 today with your translations included. The next release planned is 1.0 which I'm hoping will happen within the next few weeks, I'll ask you to update the translations before then.

We'll look into using a translation service but I'll tag you on a github issue before any release that needs translation updates.

**Comment by oonid** [comment]
hi @JakeUrban 
I'm sorry, I think I have missed editing the docs (internationalization),
should I create another PR?
thank you.

**Comment by JakeUrban** [comment]
Sure, open another PR.

**Pull request merged**
