### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by ronaldoy**

### CODE REVIEW

**Comment by JakeUrban** [comment]
Hi @ronaldoy can you delete the changes you made to the `id` transaction file?

**Comment by JakeUrban** [comment]
Hi @ronaldoy can you delete the changes you made to the `id` transaction file?

**Comment by JakeUrban** [comment]
We just had another dev update the `id` translation files so if we merged your PR as it is now it would overwrite the updates.

**Comment by ronaldoy** [comment]
I know. I am pushing a new update.

**Pull request closed without merging**
