### PR TITLE
SEP-24 asset symbol styling

### PR DESCRIPTION
**Pull request by yuriescl**
Improve asset symbol appearance inside the amount input.

Current:
Screenshot_15

Proposed by this pull request:
Screenshot_14

### CODE REVIEW

**Comment by yuriescl** [comment]
@JakeUrban How do I compile the SCSS changes? I used `sass` CLI directly but it creates new lines for the curly braces.

**Comment by JakeUrban** [comment]
Hey @yuriescl, thanks for this, I agree its an improvement.

I actually haven't used the CLI recently, can you provide the commands to reproduce?

I usually go into the python shell and use the `sass` module programatically:

```python
import sass

sass.compile("<path to .scss file>")
```

**Comment by yuriescl** [comment]
@JakeUrban I did this:
```
npm install -g sass
sass base.scss base.css
```
But it puts the closing curly braces in new lines:
image

**Comment by JakeUrban** [comment]
Oh I see. The python package has its own CLI but I haven't gotten it to work. Something like `python manage.py compilesass`

**Comment by yuriescl** [comment]
I ran `pipenv sync -d`, then added `sass_processor` to `INSTALLED_APPS`, then ran ` python manage.py compilescss polaris/static/polaris/base.scss`, but got `manage.py compilescss: error: unrecognized arguments: polaris/static/polaris/base.scss`.
I'm still stuck trying to compile that `base.scss` file.

**Review by JakeUrban — APPROVED** [review]

**Comment by JakeUrban** [comment]
@yuriescl can you merge the lastest of master into this branch? Then I can merge it into master.

**Comment by yuriescl** [comment]
@JakeUrban Updated. I changed the JS syntax a little bit for readability, but I can revert if you prefer, not sure if you like to keep `let` declarations at the beginning of functions, etc.

**Comment by yuriescl** [comment]
> @JakeUrban Updated. I changed the JS syntax a little bit for readability, but I can revert if you prefer, not sure if you like to keep `let` declarations at the beginning of functions, etc.

Just updated again, I guess it's better to declare at the beginning of scope instead of inside an `if`.

**Review by JakeUrban — APPROVED** [review]

**Comment by JakeUrban** [comment]
@yuriescl I've compiled the sass, but I actually updated the asset code background color to use our `$light-gray` preset color.

Screen Shot 2022-03-03 at 10 35 42 AM

**Pull request merged**
